name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP with compatible Redis extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: |
            redis:6.1.4 # Explicitly install version 6.1.4 or newer
        # link to documentation for shivammathur/setup-php:
        # github.com

#    - name: Stop default Redis service
#      # The ubuntu-latest image has a pre-installed redis-server system service
#      # that runs automatically and is likely the old version causing conflicts.
#      run: sudo service redis-server stop || true

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    - name: Run grumphp composer,file_size,phpcpd,phpcs,phpmnd,securitychecker_enlightn,securitychecker_roave,yamllint
      run: vendor/bin/grumphp run --tasks=composer,file_size,phpcpd,phpcs,phpmnd,securitychecker_enlightn,securitychecker_roave,yamllint

    - name: Run grumphp phpstan
      run: vendor/bin/grumphp run --tasks=phpstan

    - name: Run grumphp phpunit
      run: vendor/bin/grumphp run --tasks=phpunit

    - name: Run grumphp infection
      run: vendor/bin/grumphp run --tasks=infection

    - name: Run grumphp rector
      run: vendor/bin/grumphp run --tasks=rector

    # - name: Run test suite
    #   run: composer run-script test
